In [15]:
import torch
import numpy as np
import random
import itertools
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
import numpy as np
from tqdm import tqdm
from sklearn.preprocessing import StandardScaler
import sys
import os
os.chdir('d:\\1st\\BPs_BPTK')
sys.path.append("Python") 
from BPS_init_function import BPS_BPTK 
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif']=['SimHei'] # 用来正常显示中文标签
plt.rcParams['axes.unicode_minus']=False # 用来正常显示负号
import keyboard


# 准备数据
y1 = np.load("Python\ForwardFitNN\WithTime\Database\ForwardLabel_zzc.npy")  #输入标签数据
y2 = np.load("Python\ForwardFitNN\WithTime\Database\ForwardLabel_SG.npy")  #输入标签数据
y = np.vstack((y1,y2))

X1 = np.load("Python\ForwardFitNN\WithTime\Database\ForwardInput_zzc.npy")
X2 = np.load("Python\ForwardFitNN\WithTime\Database\ForwardInput_SG.npy")
X =  np.vstack((X1,X2))

# 数据预处理 标准化数据


def standard_transform(x):
    # 计算每个特征的均值
    mean = x.mean(dim=0)
    # 计算每个特征的标准差
    std = x.std(dim=0, unbiased=False)  # unbiased=False 相当于 numpy 的 ddof=0
    # 避免使用0的标准差
    std[std == 0] = 1
    # 进行标准化转换
    x = (x - mean) / std
    return x,mean,std

def inverse_transform(x, mean, std):
    # 将标准化后的张量乘以标准差，然后加上均值
    x = x * std + mean
    return x


In [51]:
a  = torch.tensor([[4,1,6],
                  [111,0.6,1],
                  [74, 22, 1.999],
                  [0,3,0],
                  [99999,100,100]])

x,mean,std = standard_transform(a)

In [46]:
x

tensor([[-1.3297, -0.6870,  1.3888],
        [ 1.0818, -0.7270, -0.9256],
        [ 0.2479,  1.4140, -0.4632]])

In [47]:
std

tensor([44.3697,  9.9951,  2.1604])

In [52]:
a = inverse_transform(x, mean, std)
print(a)

tensor([[4.0000e+00, 1.0000e+00, 6.0000e+00],
        [1.1100e+02, 6.0000e-01, 1.0000e+00],
        [7.4000e+01, 2.2000e+01, 1.9990e+00],
        [0.0000e+00, 3.0000e+00, 1.9073e-06],
        [9.9999e+04, 1.0000e+02, 1.0000e+02]])
